#!usr/bin/python3
import re, json, requests, time
from TClickHouse import ClickHouse
from datetime import datetime
import pandas as pd


class YandexDirectReports:
    def __init__(self, access_token, client_login, client_name, connect_params):
        self.url = "https://api.direct.yandex.com/json/v5/"
        self.client_id = re.sub('[.-]', '_', client_login)
        self.ch = ClickHouse(connect_params["host"], connect_params["user"], connect_params["password"])
        self.data_set_id = f"{client_name}_YaDirect_{self.client_id}"
        self.client_name = client_name
        self.connect_params = connect_params

        self.headers_report = {
            "Authorization": "Bearer " + access_token,
            "Client-Login": client_login,
            "Accept-Language": "ru",
            "processingMode": "auto",
            "returnMoneyInMicros": "false",
            "skipReportHeader": "true",
            "skipReportSummary": "true"}

        create_data = self.ch.create_data_set_and_tables(self.data_set_id, self.report_dict, self.client_name,
                                                         "YaDirect", self.client_id)
        assert create_data == [], "Error"

    def __create_body(self, selection_criteria, field_names, report_name, report_type):

        body = {
            "params": {
                "SelectionCriteria": selection_criteria,
                "FieldNames": field_names,
                "ReportName": (self.body_report_name),
                "ReportType": report_type,
                "DateRangeType": "CUSTOM_DATE",
                "Format": "TSV",
                "IncludeVAT": "NO",
                "IncludeDiscount": "NO"
            }
        }
        jsonBody = json.dumps(body, ensure_ascii=False).encode('utf8')
        return jsonBody

    def __request(self, selection_criteria, field_names, report_name, report_type, method):
        jsonBody = self.__create_body(selection_criteria, field_names, report_name, report_type)
        try:
            data = requests.post(self.url + method, jsonBody, headers=self.headers_report)

        except requests.exceptions.ConnectionError as error:
            print(error)
            data = requests.post(self.url + method, jsonBody, headers=self.headers_report)

        if data.status_code in [201, 202]:
            time.sleep(60)

            return self.__request(selection_criteria, field_names, report_name, report_type, method)
        return data

    def get_report(self, report_name, date_from, date_to):
        """
        report_name - report_type - fields:
         - CAMPAIGN_STAT - CUSTOM_REPORT
         - CAMPAIGN_DEVICE_AND_PLACEMENT_STAT - CUSTOM_REPORT
         - CAMPAIGN_GEO_STAT - CAMPAIGN_PERFORMANCE_REPORT
         - CAMPAIGN_PLACEMENT_STAT - CAMPAIGN_PERFORMANCE_REPORT
         - CAMPAIGN_SOCDEM_DEVICE_STAT - CAMPAIGN_PERFORMANCE_REPORT
         - AD_STAT - AD_PERFORMANCE_REPORT
         - AD_DEVICE_STAT - AD_PERFORMANCE_REPORT
         - REACH_AND_FREQUENCY_STAT - REACH_AND_FREQUENCY_PERFORMANCE_REPORT
         - KEYWORD_AD_STAT - CUSTOM_REPORT
         - KEYWORD_SOCDEM_STAT - CUSTOM_REPORT
         - KEYWORD_DEVICE_STAT - CRITERIA_PERFORMANCE_REPORT
         - KEYWORD_DEVICE_AD_STAT - CUSTOM_REPORT

         date format: "YYYY-MM-DD"

        """

        get_data_params = self.report_dict.get(report_name, False)
        if get_data_params:
            report_type = get_data_params['type']
            selection_criteria = {"DateFrom": date_from, "DateTo": date_to}
            field_names = [i['name'] for i in get_data_params['fields']]

            self.body_report_name = datetime.strftime(datetime.now(), format="%Y-%m-%d %H:%M:%S")
            data = self.__request(selection_criteria, field_names, report_name, report_type, "reports")

            if 'error' in data.text:
                error_code = json.loads(data.text)['error']['error_code']
                error_detail = json.loads(data.text)['error']['error_detail']
                stat = pd.DataFrame()
                response = [stat, error_code, error_detail]

            else:
                report_data_split = data.text.split('\n')
                data_split = [x.split('\t') for x in report_data_split]
                stat = pd.DataFrame(data_split[1:-1], columns=data_split[:1][0])

                result = self.ch.insert_dataframe(stat, self.data_set_id,
                                                  f"{self.client_name}_YaDirect_{self.client_id}_{report_name}")

                response = [stat, data.status_code, "Success"]

            return response

        else:
            stat = pd.DataFrame()
            return [stat, 0, "Указан недопустимый тип отчета."]


